### ISSUE TITLE
Please use color picker

### ISSUE THREAD

**Issue by hugoatjoget** [jogetoss/JSON-to-Table-Formatter#2]
https://github.com/jogetoss/json-to-table-formatter/blob/726471427cb87a63381becd653f93cbc07f1c9cb/src/main/resources/properties/JsonToTableFormatter.json#L22

**Comment by miaoxng** [comment]
fixed in version 7.0.0 commit: https://github.com/jogetoss/JSON-to-Table-Formatter/commit/26baca6e4c54f9406d90c0dc479ee8a970a3bfdb
